### ISSUE TITLE
Error starting with v1.4.2

### ISSUE THREAD

**Issue by jkudish** [florianv/exchanger#102]
Hello, I started getting this error once upgraded to v1.4.2:

```
TypeError: Argument 1 passed to Exchanger\Service\PhpArray::__construct() must be of the type array, object given, called in .../vendor/florianv/swap/src/Service/Factory.php on line 100
```

After I downgraded to v1.4.1 the error goes away. I only see a small change to the cache in 1.4.2. so I am not too sure why this error is happening. 
I'm using *this* package through your `florianv/swap` package which is at v3.5.0.

Any ideas?

**Comment by ostrolucky** [comment]
Same here. @florianv please try to not make these kind of changes in patch releases. There are very heavy changes in 1.4.2 https://github.com/florianv/exchanger/compare/1.4.1...1.4.2

**Comment by ostrolucky** [comment]
what's the correct diff link?

**Comment by florianv** [comment]
Actually, I noticed the mistake. The correct version that should have been tagged should be `2.2.2` instead of `1.4.2` - I will delete `1.4.2`.

**Comment by florianv** [comment]
@jkudish @ostrolucky Sorry for the mistake, please downgrade to `1.4.1` and things should be back as normal!

**Comment by jkudish** [comment]
Thanks @florianv
