### ISSUE TITLE
The historical url for ECB could be changed so it's not limited to 90 days back

### ISSUE THREAD

**Issue by bozhidargyurov** [florianv/exchanger#103]
I think the historical URL for ECB could be changed to `https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml`, so it's not limited to 90 days back and the functionality could be more usable and useful. 
Currently if I want to fetch the exchange rates for 2019-01-30, I'm not able, because the feed that currently is being used is limited to 90 days back.

**Comment by florianv** [comment]
@bozhidargyurov I think it's a good idea!

The response for this url is pretty big so it would slow down most requests.

Maybe we could change the used url dynamically if we try to request historical data > 90 days ?

I would be happy if you could send a PR :)

**Comment by bozhidargyurov** [comment]
@florianv I've opened a PR https://github.com/florianv/exchanger/pull/106
