### ISSUE TITLE
[BUG] The float problem

### ISSUE THREAD

**Issue by TimurFlush** [florianv/exchanger#127]
Hello!

As you all know, converting string type to float makes the resulting number less accurate or can lead to some other side effects.

Please see it:
https://github.com/florianv/exchanger/blob/e47537909d6b5d6d5050308020d323e7b75e6176/src/ExchangeRate.php#L62
https://github.com/florianv/exchanger/blob/e47537909d6b5d6d5050308020d323e7b75e6176/src/Service/Cryptonator.php#L62

```shell
php -r "echo (string)0.00000050;" # prints 5.0E-7
```

I propose to make the resulting class accept only string. As a result, we'll get the course in its original form and let the developers not worry about it.

**Comment by TimurFlush** [comment]
@florianv How soon can you approve the pull-request if I send it to you?

**Comment by florianv** [comment]
@TimurFlush We'll need to release a new major version for that, since it will break backward compatibility :/
