### ISSUE TITLE
[BUG] Cryptonator resources are outdated

### ISSUE THREAD

**Issue by TimurFlush** [florianv/exchanger#128]
Hello!

I see that the last time the list of supported cryptonator currencies was updated was several years ago.
In this regard, I catch an error when requesting the rate of the currency pair BTC/TRX and others.

I propose:

- Add a new `disable_supporting_check` option to the Cryptonator service so that it does not check if these currencies exist in the outdated list.

- Allow the developer to provide this service with a map of supported currencies independently.

- Remove this check altogether.

@florianv How do you like this?

**Comment by florianv** [comment]
Hey @TimurFlush, I think we can simply remove the check and allow the request to be made.
It will be easier than having to maintain the list that is constantly changing!

**Comment by florianv** [comment]
@TimurFlush Fixed in the latest version!
