### ISSUE TITLE
ExchangeRatesApi support free plan

### ISSUE THREAD

**Issue by Seagull-4auKa** [florianv/exchanger#135]
It looks like ExchangeRatesApi is now running on apilayer (**Fixer**, **CurrencyLayer**). And support the FREE plan only without httpS.
Response when using **ExchangeRatesApi** with a FREE plan: `{"error":{"code":"https_access_restricted","message":"Access Restricted - Your current Subscription Plan does not support HTTPS Encryption."}}`

Therefore, like **Fixer** and **CurrencyLayer**, **ExchangeRatesApi** should use the `enterprise` option and different endpoints.
By the way, 'supportQuery' should use such a condition:
`$this->options['enterprise'] || 'EUR' === $exchangeQuery->getCurrencyPair()->getBaseCurrency();`

https://exchangeratesapi.io/documentation/#ssl
https://exchangeratesapi.io/documentation/#api_response

**Comment by karser** [comment]
Encountered the same issue, will try your PR

**Comment by Seagull-4auKa** [comment]
Just now I noticed that when executing php cs fix, the method names in the tests changed to camelCase. I will try to fix and commit today

**Comment by florianv** [comment]
It's merged and `2.7.0` released!
