### ISSUE TITLE
NonBreakingInvalidArgumentException for what?

### ISSUE THREAD

**Issue by Seagull-4auKa** [florianv/exchanger#137]
ExchangeRatesApi using `NonBreakingInvalidArgumentException` instead of `\InvalidArgumentException`
https://github.com/florianv/exchanger/blob/082894c630e9dc03154ef75b1bbb5586b7c2841a/src/Service/ExchangeRatesApi.php#L52-L54
But other services normally use `\InvalidArgumentException`
https://github.com/florianv/exchanger/blob/082894c630e9dc03154ef75b1bbb5586b7c2841a/src/Service/Fixer.php#L49-L51
https://github.com/florianv/exchanger/blob/082894c630e9dc03154ef75b1bbb5586b7c2841a/src/Service/CurrencyLayer.php#L48-L50

I saw comments in https://github.com/florianv/exchanger/pull/133, but `NonBreakingInvalidArgumentException` extends `\Exception` instead `Exchanger\Exception\Exception`. 
https://github.com/florianv/exchanger/blob/082894c630e9dc03154ef75b1bbb5586b7c2841a/src/Exception/NonBreakingInvalidArgumentException.php#L21

As for me, throwing `\InvalidArgumentException` (`extends \LogicException`) is normal behavior. Given that this happens during initialization, since `processOptions` is called from the constructor.
All other classes also throw `\InvalidArgumentException` or `\LogicException` (`Exchanger\Service\HttpService`).
And I don't understand how using `NonBreakingInvalidArgumentException` would help when using `Swap\Builder` (https://github.com/florianv/exchanger/pull/133)

Or did I miss something?

**Comment by florianv** [comment]
@Seagull-4auKa This exception is to prevent breaking the services chain, for example when a SaaS suddently changes their API (breaking BC) and we need to change the $options requirements. A normal \InvalidArgument exception would break the whole chain so the other services won't have a chance to be executed as fallback.

**Comment by Seagull-4auKa** [comment]
> A normal \InvalidArgument exception would break the whole chain so the other services won't have a chance to be executed as fallback.

Sorry, but I don't see how `NonBreakingInvalidArgumentException` can help in this case. `NonBreakingInvalidArgumentException` will break chain too, isn't it?
