### ISSUE TITLE
Error with the Access Key

### ISSUE THREAD

**Issue by Xernito** [florianv/exchanger#141]
Hallo,

I use https://github.com/Part-DB/Part-DB-symfony on my private server. But I got an error, that the access key in ExchangeRatesApi.php Linie 52 is not defined.
But I insert a API Key from exchangeratesapi.io in: const ACCESS_KEY_OPTION = 'access_key';

What am I doing wrong? 

 I also changed this Line
 const LATEST_URL = 'https://api.exchangeratesapi.io/latest?base=%s&access_key=%s&symbols=%s';
in
const LATEST_URL = 'http://api.exchangeratesapi.io/latest?base=%s&access_key=%s&symbols=%s';
because https is not supportet in the basic model.

Stephan

**Comment by florianv** [comment]
Hi @Xernito, 
I suggest to open an issue to PartDB - they may have a specific configuration for the access key requires by ExchangeRatesApi.
