### ISSUE TITLE
psr/simple-cache ^1.0

### ISSUE THREAD

**Issue by goaround** [florianv/exchanger#142]
Hi,

The composer.json file locks `psr/simple-cache` to ^1.0, but there is already ^2 and ^3 available. I can't install e.g. `google/apiclient` because it requires ^3.0

**Comment by florianv** [comment]
@goaround Hi, can you please send a PR to allow for the 3 versions if they work with Swap?

**Comment by francoisauclair911** [comment]
@florianv I tried pulling the repo to then make some PR but I cannot seem to make the tests pass before having modified anything

```Exchanger\Tests\Service\CentralBankOfCzechRepublicTest``` seems to be failing over and over

**Comment by goaround** [comment]
@florianv sure, I tested it with ^2.0 as well

**Comment by florianv** [comment]
Thanks! I'm closing the ticket due to the recent merge :)
