### ISSUE TITLE
suggestions for currencies not supported by services you use?

### ISSUE THREAD

**Issue by shez1983** [florianv/exchanger#15]
Have an issue whereby we allowed users to buy in AED (dirhams?) but none of the services you support currently use that? not sure whats the best way to go about it

**Comment by florianv** [comment]
We could list all supported currencies per service but it seems to be a huge task and it's likely to change over time so not easy to maintain.

Maybe you could use a list of currencies that you want to support and run a test against your Swap to see which ones are supported.

Maybe you have a better idea.

Anyway if you know any provider supporting AED we can implement it and include it in Swap.
