### ISSUE TITLE
php-http/message-factory is abandonned

### ISSUE THREAD

**Issue by dehy** [florianv/exchanger#153]
`php-http/message-factory` is abandonned. Suggested replacement is `psr/http-factory`.

Source: composer and https://github.com/php-http/message-factory

**Comment by dehy** [comment]
Linked to this upstream issue https://github.com/php-http/client-common/issues/227

**Comment by JexPY** [comment]
Got the error message on composer update.
```
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
```
