### ISSUE TITLE
Support crypto currency

### ISSUE THREAD

**Issue by awmedia** [florianv/exchanger#18]
Great library!

I was wondering why the length of a currency in a currency pair is limited to 3 characters?
It would be a lot more flexible when removing this limitation to allow for example crypto currencies (DASH, STRAT, STEEM, etc).

Example implementation for the createFromString method in CurrenyPair:
```
public static function createFromString($string)
{
    $matches = [];
    if (!preg_match('#^([A-Z]+)/([A-Z]+)$#', $string, $matches)) {
        throw new \InvalidArgumentException('The currency pair must be in the form "EUR/USD".'); 
    }

    $parts = explode('/', $string);

    return new self($parts[0], $parts[1]);
}

**Comment by florianv** [comment]
Hey @awmedia,

this is indeed something that is not supported right now. I don't think our providers support retrieving them (not tested yet).

Definitely something we can add support to, given we have at least one provider allowing to retrieve rates for these currencies

**Comment by sudden-break** [comment]
Maybe we can integrate a service like
https://www.cryptonator.com/api/

They have USD and EUR Conversion for about 500 Cryptocurrencies.

**Comment by florianv** [comment]
@sudden-break Looks like a good idea!

**Comment by dannyweeks** [comment]
I have made a start on this on a fork. Will submit a PR when I have something solid hopefully over the next few days!

**Comment by florianv** [comment]
@dannyweeks Thanks for digging into that! I think we are safe to remove the 3 chars constraint on currency codes as some cryptos have more than 4 chars. Unless we can build a list of all currencies and crypto currencies to validate the codes

**Comment by dannyweeks** [comment]
No worries, it should be quite fun! 

Regarding codes the API does have a [list of the currencies](https://www.cryptonator.com/api/currencies) (although bot protected looking at the source) they accept which I need to use in some way for the `Cryptonator::supportQuery` method. 

I haven't quite figured out what the _primary_ and _secondary_ statuses mean as it doesn't seem to correlate to if you can use them as base currencies. Doesn't seem to be any documentation around this endpoint.

Just trying to figure a nice way to store the supported currencies.

**Comment by florianv** [comment]
Fixed by https://github.com/florianv/exchanger/pull/29
