### ISSUE TITLE
 requires payum/core ^1.4 -> satisfiable by payum/core and php-http/client-implementation ^1.0 -> no matching package found

### ISSUE THREAD

**Issue by viral2014** [florianv/exchanger#25]
Hello,

When I make composer require payum/payum-bundle I get the following error.
![issuegit](https://user-images.githubusercontent.com/31303925/29653234-a293f2b2-88c6-11e7-822f-0f1260dd33b2.png)

**Comment by florianv** [comment]
Hello,

`
$ composer require payum/payum-bundle php-http/message php-http/guzzle6-adapter
`
