### ISSUE TITLE
Google changed URL of the convertrer

### ISSUE THREAD

**Issue by skvorets** [florianv/exchanger#30]
Google service recently started to throw an error 
  [Exchanger\Exception\ChainException]
  The chain resulted in 1 exception(s):
  Exchanger\Exception\Exception: The currency is not supported or Google changed the response format. 

This is because Google changed the URL of endpoint
and now http://www.google.com/finance/converter 
gives 302 page:
```
  <HTML><HEAD><meta http-equiv="content-type" content="text/html;
  charset=utf-8">
  <TITLE>302 Moved</TITLE></HEAD><BODY>
  <H1>302 Moved</H1>
  The document has moved
  <A HREF="http://finance.google.com/finance/converter">here</A>.
  </BODY></HTML>
```

**Comment by skvorets** [comment]
Apparently my Swap was up to date but Exchanger itself was not. 
v0.7.0 has the new URL, sorry.

**Comment by florianv** [comment]
@skvorets Yes it has been changed to use the new url, thanks
