### ISSUE TITLE
Yahoo have (apparently) switched off the Yahoo Finance API

### ISSUE THREAD

**Issue by kinglozzer** [florianv/exchanger#31]
Results always seem to be `null` now: https://developer.yahoo.com/yql/console/?q=show%20tables&env=store://datatables.org/alltableswithkeys#h=select+*+from+yahoo.finance.xchange+where+pair+in+(%22GBPUSD%22).

See also https://yahoo.uservoice.com/forums/382977-finance/suggestions/19346998-reintroduce-the-old-yahoo-finance-api. I’m not familiar with Yahoo’s products, so I can’t verify any of this (I just started getting errors because my site was relying on Yahoo). May be worth updating the docs if it is the case :)

---

Edit: The actual fatal error I was experiencing has been fixed in https://github.com/florianv/exchanger/issues/19

**Comment by ahubers** [comment]
This seems to be the case. You can check the endpoint directly as it is used in this library --

```php
    const URL = 'https://query.yahooapis.com/v1/public/yql?q=%s&env=store://datatables.org/alltableswithkeys&format=json';
    /**
     * {@inheritdoc}
     */
    public function getExchangeRate(ExchangeRateQuery $exchangeQuery)
    {
        $currencyPair = $exchangeQuery->getCurrencyPair();
        $queryPairs = sprintf('"%s%s"', $currencyPair->getBaseCurrency(), $currencyPair->getQuoteCurrency());
        $query = sprintf('select * from yahoo.finance.xchange where pair in (%s)', $queryPairs);
        $url = sprintf(self::URL, urlencode($query));
```

which produces https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.xchange where pair in ("USDEUR")&env=store://datatables.org/alltableswithkeys&format=json

**Comment by florianv** [comment]
@ahubers I think it has be discontinued yes..Without any clear announcement on their end, it's annoying.

I think we need to remove it from the documentation in Exchanger and Swap
