### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by sagikazarmark** [florianv/exchanger#38]
There is a pull request in [moneyphp/money](https://github.com/moneyphp/money/pull/369) which adds this package as a dependency.

However, I just realized that this package has not seen a stable release yet, but based on the recent history, the API seems quite stable to me and the fact that there are deprecations instead of just removed code suggests the same.

Is there a plan to tag a stable version of this package? I know it is used internally in Swap, so I have no doubts about stability, but it still feels weird to rely on an "unstable" version.

**Comment by florianv** [comment]
Hey @sagikazarmark,

yes you are right it has been stable for a few years now. I just tagged `1.0.0`

**Comment by sagikazarmark** [comment]
Great! Thanks a lot!
