### ISSUE TITLE
php-http/client-implementation ^1.0 -> no matching package found.

### ISSUE THREAD

**Issue by rogervila** [florianv/exchanger#4]
Hello, 

When I make `composer require florianv/swap` I get the following error.

![captura de pantalla 2016-11-10 a las 16 12 38](https://cloud.githubusercontent.com/assets/6053012/20182110/f7553934-a760-11e6-9025-74360ae5c0a2.png)

How can I install this [virtual package](https://packagist.org/providers/php-http/client-implementation)?

Thank you.

**Comment by florianv** [comment]
Hey,

as you can see on the documentation you need to install multiple packages

https://github.com/florianv/exchanger/blob/master/doc/readme.md#installation

**Comment by rogervila** [comment]
Sorry, I forgot to close it. Thank you very much

**Comment by florianv** [comment]
You are welcome :)
