### ISSUE TITLE
Exchanger\Exception\ChainException

### ISSUE THREAD

**Issue by mukeshj17m** [florianv/exchanger#59]
Till today morning everything was working fine and there were no issues but suddenly my site stopped working. When i checked the log i could see the following errors. 

Exchanger\Exception\ChainException: The chain resulted in 1 exception(s):
Exchanger\Exception\UnsupportedCurrencyPairException: The currency pair "USD/EUR" is not supported by the service "Exchanger\Service\Fixer". in /var/www/project/project-files/vendor/florianv/exchanger/src/Service/Chain.php:66

Anyone facing the same issue.

**Comment by sasin91** [comment]
Your issue is Fixer.

it only supports base EUR on free plan now, you should upgrade to enterprise or change service.
