### ISSUE TITLE
Getting ChainException with empty information about what happened

### ISSUE THREAD

**Issue by danaki** [florianv/exchanger#67]
Seems a service I'm using has no support of given pair. $e->getExceptions() returns empty list, no sane details. A message would be great to have.

**Comment by florianv** [comment]
@danaki I agree! 
Can you maybe track it down and send a pull request ? 
Thanks!

**Comment by florianv** [comment]
@danaki FYI, this will be fixed in the next version.

I think if you upgrade to the latest 1.x version, you should be able to retrieve the merged message from the chain, using `$e->getMessage()` too.
