### ISSUE TITLE
Integrate with PSR-18 and PSR-17

### ISSUE THREAD

**Issue by gmponos** [florianv/exchanger#70]
Do you have any plans here?

Checking the code very quickly I don't have a feeling that his can be done without a BC..

**Comment by florianv** [comment]
@gmponos Not yet but we can break BC there as it will be included in a new major version

**Comment by gmponos** [comment]
I will try my best...

**Comment by gmponos** [comment]
We need to wait for this.. https://github.com/php-http/curl-client/pull/52

I will start working on it never the less.

**Comment by florianv** [comment]
@gmponos FYI, the most recent code in development is in the master branch.
