### ISSUE TITLE
Currency Converter API service started to ask for a Free API KEY (required)

### ISSUE THREAD

**Issue by lptn** [florianv/exchanger#83]
```json
{
"status": 400,
"error": "Free API Key is required. Obtain your free API key at https://free.currencyconverterapi.com"
}
```

URL example: https://free.currencyconverterapi.com/api/v6/convert?q=INR_USD&date=2018-02-14

Get KEY URL: https://free.currencyconverterapi.com/free-api-key

PS: I'm working on PR

**Comment by florianv** [comment]
This was fixed in both 1.x and 2.x (and released) so I'm closing the issue!
