### ISSUE TITLE
Google updated the format?

### ISSUE THREAD

**Issue by johnnyteoh** [florianv/exchanger#98]
Hi, just noticed my daily batch job for SWAP with Google, seems to be failing this morning, does anyone else experienced the problem? Seems like the following line in Google adapter is returning 0 in length.

 $nodes = $xpath->query('//span[@id="knowledge-currency__tgt-amount"]');

**Comment by kslimani** [comment]
It seems that Google service is deprecated since #68.

A deprecation notice was previously added in https://github.com/florianv/exchanger/commit/1c6fefb470f43e95460ea6f69b878cc13d237a29.

I recommend you use [another service](https://github.com/florianv/exchanger#services).

**Comment by johnnyteoh** [comment]
Thanks, I will move the code to connect to Currency Converter API then.
